language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: dKFJheqYtv6uKOPORx3iZCjwT3ZhZ2B2iqmHtfDQvRzbJPIzJDSnr/VLLoFo2qbkyHbH5XE3q6M/bDLAMyC2qUWoDfecYbak0HtVxiFF7us7pgfeQs46K2R4S9nndriD68dh9m3O9J+L12OPcT68F2CKaJtmuIq5yXQCwkVe1l013KcwHKwySc+wUQFPkrZUzoL0uOc9O2vxFDLoJXR2uzSiyWeHIhVt3gl+irPRjVk9rrWHHpfQbKNRiI+GomSAWFJSl0ALmRaN6gLpDolZFn0fLAr5tc512XTrp6HsuFibe3ID3k1RvK1EMFiKaCCP6GQxa++OVANB6PiVQ3YaZlgC3g0bceeI8fat9fYJaVeDybNVxcw4xq8o9XpHoV4dE1NCQ5Qmn6/aQtkg7y5XXzfKhdyOLzc5AgHll/67xEgPW4n0+JVTdn+k4YLrwz4rMRfqTWakPI1f3a5vDAwq1PhYSmkEn5jQwr5ZZcyvFOCbWFvn+U/ZSsr2kofCqrQkagGGHt/nQohlgD0wudikGrSCIj+6c7fiN3hML/aA7Y/y22+o1sWbYE7jhS/hPU6rIU/5KJcU6Zvotb3HsJWjNOf0xo2KrZyS+NVlFYqOcqP/vUGWjAYZk+xV5hm2XFSqDcg2SWhynFwKgzA5n42ShORTTiC6HpuY30JNSYmQ578=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: s9cSGTKUMyaZP+SC23F6vsHIPXjOdjfsdI5V5hTrdlwqcEZVnXW6bmK8UFuHuw83/lxwd4qORkf9YZhbOvjPY8rLCWHkqFtZgGA+25MRP8FV//Y2UAS9nS3bjX657Ri0edFbQ21ymlp/2zG4b9CsbVrJs4N8g5OVZ2OJ1UPZfq4UzoFZO2r+HTEt1eXa1LxPEOqF2odVDqZr/wXwOKu5t3B9Cuqu+BXqRePfnewZUfVA0kQnRVWsBMjhs6QLbiqvW7S6wVL7Wxr86rUX/AxLdV0ybBBC/QqVqt9I9M/MMF/I1dpVS9KxwBWrT1JV1olmWb0QFpqoHlIpFfiTr5dkfWo4PDLTQbPaAyyLJiWqZBGaeAZCm7C3TKvMfuLMP3RY/Yerpi1xyC5y2qoOBEY3827VgeYO2WSSwqNiBkDO/DuFZzUMPLxLISRUrF48uhzyVYHJizOcRQGJEgtZ6goZguEdsfoOkuR/kBRodMV/++uUlioPBaZCdQQ60e8exmtTMgoPBqGYJWZbPpGsJQjUQiCpvSMV5hvYhoS6I2hwO9qW/Rq+3e8hd+xpxUm31fOh7VyTc0/euDPkvqSyM3lfH4rYI57X+ev4qepUr+dS8k+PMvUDyD7ed8qGdzDuHrGrMtVMUhL9lQ1SuYQXa9GlAdJY45dQSJ2CYwTf38mNzSE=
sudo: false
