language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: b8i63ODeviGL0cK+ZOx9ikWkXOt2waDIn9v2tXrlJEL25QasPD4zhuKLeRJjPSDJ26I7YR8Ltcs7A+xj9DnAfMTgOWDojiG7lBwCLW89OsG/EUrGj6RLugZjXtwQlSkQVPmV4go7SU5++DrMsW2rmX+HrTVnzQHe0lTVclL4T7pIzd5GcAuImdPVPZuxMtcwIYFUG3iCnTFoGpERTKAzYwqvYx3snzajtVvX9Usga7INZhudEZpIH3mI3FRbjFndE/ZaKKKOBwcVYeJYKwszx8piMy9Z/Cv3ZlRAsD+GOtDUq17PaOVHTSMpLK3i4U+Q5gidShM+y+IJhzroRh81LbMsq/3x53BET+YG/Dk75x7EbejGClniR1cpDHCvlYN2Fmrl+9EZ0qnXyNA+941+kwcI2XNA0OQtjM2lr6KbGAY02bmejYwtpIzF1EAJKHT/0CXbi8y48yxYrwFDqeWd+lqqB3xQWwzxyAFM4WtwRPByGwt3DkD2Sn82FquTpOzGOUkmoKjZQ1ZOxqbnpddSqLVg0MKRAtCjqBH4qrjATAHBFsz3wJPJ8r2ooVJxrDy4NFKk8CE1z98Zrxv3RZr/nRW7VLdDJccfenfd7EZFv4SrSw5HabCjgiY2YDnY5jQCxk3RFYYTK3WMVgOwW34FyV1RIWRcu7EZZsre6uvOlXE=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: s9cSGTKUMyaZP+SC23F6vsHIPXjOdjfsdI5V5hTrdlwqcEZVnXW6bmK8UFuHuw83/lxwd4qORkf9YZhbOvjPY8rLCWHkqFtZgGA+25MRP8FV//Y2UAS9nS3bjX657Ri0edFbQ21ymlp/2zG4b9CsbVrJs4N8g5OVZ2OJ1UPZfq4UzoFZO2r+HTEt1eXa1LxPEOqF2odVDqZr/wXwOKu5t3B9Cuqu+BXqRePfnewZUfVA0kQnRVWsBMjhs6QLbiqvW7S6wVL7Wxr86rUX/AxLdV0ybBBC/QqVqt9I9M/MMF/I1dpVS9KxwBWrT1JV1olmWb0QFpqoHlIpFfiTr5dkfWo4PDLTQbPaAyyLJiWqZBGaeAZCm7C3TKvMfuLMP3RY/Yerpi1xyC5y2qoOBEY3827VgeYO2WSSwqNiBkDO/DuFZzUMPLxLISRUrF48uhzyVYHJizOcRQGJEgtZ6goZguEdsfoOkuR/kBRodMV/++uUlioPBaZCdQQ60e8exmtTMgoPBqGYJWZbPpGsJQjUQiCpvSMV5hvYhoS6I2hwO9qW/Rq+3e8hd+xpxUm31fOh7VyTc0/euDPkvqSyM3lfH4rYI57X+ev4qepUr+dS8k+PMvUDyD7ed8qGdzDuHrGrMtVMUhL9lQ1SuYQXa9GlAdJY45dQSJ2CYwTf38mNzSE=
sudo: false
