language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: acEp1k277TGBIqITIsw1xHW8NEaed1EMgIL+ZfyAWma1XOVt5m5LFWqXMFVA+39waBFk05auc0U11QcptBIXdTx1sTVybAWCzc5yorqmyOA55QkAFEa0GikHrN3OXVom7Dx923jPQ1SMZufU8Kp00OZQn+amH/X1T4ig93vfwBU89clHQmsjBZy6/5qbQx+G2a60cwfu0LrjuZrDoY9QQpa6kUBplkmJ7Hw4IEfInkmFHZf4ezIADPOj86uveZQkoRKIYybDio/28d+vhuAMcyr4pJ3prABy8aj1z/AOYwuwSQ8oYqo79YEkYtIL2eXyb+eNWPdKpEmajvpUXorXmMSqGgsWfyck5SXPUhZ5x7kPaMwtNcb8gRjUBKwsrxJBMDYsEWuXLAV6WRI++pmP5kSFz5DehJnIUnQkgEkkPqHSsl4Hq8dcyKVZnb59iHGIlj5abO9lqed2fQFEVB2L3GkXa34FBtZhFVdcBluH2/NPqw96vmjaDg3zuXwWNw8oq+veFd6WrwSIWI5g1CFiKfjM9fafP7VboiQSaRN9NN9tGOnWbj8dJ0aVwQOFUFdr68Uz1Z0BDp3gdMcgp1r+e3wSiQFkY7jZevzSKR67FZb5xFEGvg1l1Zpk7Ac+EPmb8+dnlBjN61wZdu83MFimSbQcPFZn8vdJ18QMvd0MsMg=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: gBnic4Dg287b4bo1x8FpB1nuaI2QHS3zxe4jIpDC7fhJsKORpUTYhNA1qJYtNEV5g954O8HAUy8YPE5OVvNO7gV2eq89V1kRllSqfVKH7aWnlUNNI6ab3IS4PxLtNIbp7KZE98bRCY+GIgG8gd9gaQ+XvmOqqYPjYGn7nbqV5IyvNvXOrYX3CWxnQ6Tg+Qw00ugwPhLlaktJpngRWZ+oKo5dIHtbLAJxe3dtfK39I3DfDNm4KCBzfpFv/UYTPAN9F0tVX5xX9GpxMFAQhRbtjvtAggfkQte0ZJwZCcU8MjkSqPhWVK5Zl2rbe2Uj+yBV/w8n/Yq5z+i3kKSABifDor0LV54u2Q1ua3Ilbq1M6VvnsHDLqG34Rdd2hSt6192sKb46AkwvonadmL1MjkFvJX0MaTjDagmL3t2Vh3QA5XFYV4LaP3Dv90kRWi4VwTgLtds2N4jKP8biRlko32bKdJNxY2asWGH+etcx9+WKlmyDli1VIYglIQf9kLazAnKc78olehczG+WgbFI0VBNMLoDAEmcRTfvGPDMnxOIe5C50VXN4roxDzGco0kc+fXhb2o/GZkOrAE063BDGnuVl20iMqkPTAEaHhMjk10kWOQ/mtGGP8nP8/5ethsX7+rShe2Mo/SI3IR3Je1+z/PRn3mSrVaO0Wa2L7fG/aLdvV5U=
sudo: false
